import React,{useEffect,useMemo,useState}from'react';
import{Users,Clock,FileText,Workflow,BarChart3,Settings,Mail,ShieldCheck,Plus,Edit,Trash2,Save,CheckCircle2,AlertTriangle,Printer,Building2,LogIn,LogOut,Search,History,Bell,MapPin,DollarSign,UserCheck,Lock,KeyRound,Copy,Download,Upload}from'lucide-react';
import{getFormTemplate,getFormBody,getFormFields,FORM_TEMPLATES}from'./formTemplates';
import{distanceMeters,calculatePayroll}from'./helpers';
import{machineId,generateActivationCode,validateActivationCode,trialStatus}from'./license';

const today=()=>new Date().toISOString().slice(0,10);
const month=()=>new Date().toISOString().slice(0,7);
const nowTime=()=>new Date().toTimeString().slice(0,5);
const uid=p=>`${p}-${Date.now()}-${Math.floor(Math.random()*9999)}`;
const defaultSettings={systemName:'Nabny HR Enterprise',company:'شركة نبني للمقاولات',activity:'مقاولات',logo:'',watermark:'NABNY',hrEmail:'hr@nabny.sa',adminEmail:'admin@nabny.sa',checkInStart:'07:30',checkInEnd:'09:00',overtimeRate:1.5,workingDays:26,trialDays:14,licenseSecret:'NABNY-CHANGE-THIS-SECRET'};
const defaultUsers=[{id:'U-ADMIN',username:'admin',password:'123456',role:'admin',name:'مدير النظام',employeeId:''},{id:'U-HR',username:'hr',password:'123456',role:'hr',name:'مسؤول الموارد البشرية',employeeId:''},{id:'U-MANAGER',username:'manager',password:'123456',role:'manager',name:'مدير موقع',employeeId:''},{id:'U-EMP',username:'employee',password:'123456',role:'employee',name:'موظف',employeeId:''}];
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
export default function App(){
 const [settings,setSettings]=useState(()=>load('v187_settings',defaultSettings));
 const [users,setUsers]=useState(()=>load('v187_users',defaultUsers));
 const [employees,setEmployees]=useState(()=>load('v187_employees',[]));
 const [locations,setLocations]=useState(()=>load('v187_locations',[]));
 const [attendance,setAttendance]=useState(()=>load('v187_attendance',[]));
 const [requests,setRequests]=useState(()=>load('v187_requests',[]));
 const [notifications,setNotifications]=useState(()=>load('v187_notifications',[]));
 const [emails,setEmails]=useState(()=>load('v187_emails',[]));
 const [forms,setForms]=useState(()=>load('v187_forms',[]));
 const [payroll,setPayroll]=useState(()=>load('v187_payroll',[]));
 const [audit,setAudit]=useState(()=>load('v187_audit',[]));
 const [license,setLicense]=useState(()=>load('v187_license',{trialStart:today(),code:'',active:false,plan:'TRIAL',expiry:''}));
 const [current,setCurrent]=useState(()=>load('v187_current',null));
 const [tab,setTab]=useState('dashboard');
 [settings,users,employees,locations,attendance,requests,notifications,emails,forms,payroll,audit,license,current].forEach(()=>{});
 useEffect(()=>save('v187_settings',settings),[settings]);useEffect(()=>save('v187_users',users),[users]);useEffect(()=>save('v187_employees',employees),[employees]);useEffect(()=>save('v187_locations',locations),[locations]);useEffect(()=>save('v187_attendance',attendance),[attendance]);useEffect(()=>save('v187_requests',requests),[requests]);useEffect(()=>save('v187_notifications',notifications),[notifications]);useEffect(()=>save('v187_emails',emails),[emails]);useEffect(()=>save('v187_forms',forms),[forms]);useEffect(()=>save('v187_payroll',payroll),[payroll]);useEffect(()=>save('v187_audit',audit),[audit]);useEffect(()=>save('v187_license',license),[license]);useEffect(()=>save('v187_current',current),[current]);
 const trial=trialStatus(license.trialStart,Number(settings.trialDays||14)); const full=license.active||trial.active;
 function addAudit(action,actor=current?.name||'النظام',risk='low'){setAudit(p=>[{id:uid('LOG'),date:today(),time:nowTime(),actor,action,risk},...p])}
 function notify({toRole,toEmployeeId,title,message,type='system'}){setNotifications(p=>[{id:uid('NOT'),date:today(),time:nowTime(),toRole,toEmployeeId,title,message,type,read:false},...p]);setEmails(p=>[{id:uid('MAIL'),to:toRole==='hr'?settings.hrEmail:settings.adminEmail,subject:title,body:message,status:'queued',date:today(),time:nowTime()},...p])}
 if(!current)return <Login users={users} setCurrent={setCurrent} settings={settings} license={license} trial={trial}/>;
 const empMode=current.role==='employee';
 const tabs=empMode?['employeeHome','employeeAttendance','employeeRequests','employeeForms','employeeNotifications']:['dashboard','employees','users','locations','attendance','requests','forms','payroll','reports','notifications','email','license','maintenance','security','settings'];
 return <div className="app"><Header settings={settings} current={current} logout={()=>setCurrent(null)} license={license} trial={trial}/><div className="layout"><aside className="sidebar">{tabs.map(id=><Nav key={id} id={id} label={labels[id]} icon={icons[id]} tab={tab} setTab={setTab}/>)}</aside><main className={!full?'locked':''}>{tab==='dashboard'&&<Dashboard employees={employees} attendance={attendance} requests={requests} payroll={payroll}/>} {tab==='employees'&&<Employees employees={employees} setEmployees={setEmployees} users={users} setUsers={setUsers} addAudit={addAudit}/>} {tab==='users'&&<UsersAdmin users={users} setUsers={setUsers} employees={employees}/>} {tab==='locations'&&<Locations locations={locations} setLocations={setLocations}/>} {tab==='attendance'&&<Attendance employees={employees} locations={locations} attendance={attendance} setAttendance={setAttendance} settings={settings} addAudit={addAudit} notify={notify}/>} {tab==='requests'&&<Requests employees={employees} requests={requests} setRequests={setRequests} notify={notify} current={current}/>} {tab==='forms'&&<Forms settings={settings} employees={employees} forms={forms} setForms={setForms}/>} {tab==='payroll'&&<Payroll employees={employees} attendance={attendance} payroll={payroll} setPayroll={setPayroll} settings={settings}/>} {tab==='reports'&&<Reports employees={employees} attendance={attendance} requests={requests} payroll={payroll}/>} {tab==='notifications'&&<Notifications notifications={notifications}/>} {tab==='email'&&<Email emails={emails}/>} {tab==='license'&&<LicensePanel settings={settings} setSettings={setSettings} license={license} setLicense={setLicense}/>} {tab==='maintenance'&&<Maintenance data={{settings,users,employees,locations,attendance,requests,notifications,emails,forms,payroll,audit,license}}/>} {tab==='security'&&<Security audit={audit}/>} {tab==='settings'&&<SystemSettings settings={settings} setSettings={setSettings}/>} {tab==='employeeHome'&&<EmployeeHome current={current} employees={employees} attendance={attendance} requests={requests} notifications={notifications}/>} {tab==='employeeAttendance'&&<Attendance employeeMode current={current} employees={employees} locations={locations} attendance={attendance} setAttendance={setAttendance} settings={settings} addAudit={addAudit} notify={notify}/>} {tab==='employeeRequests'&&<Requests employeeMode current={current} employees={employees} requests={requests} setRequests={setRequests} notify={notify}/>} {tab==='employeeForms'&&<Forms employeeMode current={current} settings={settings} employees={employees} forms={forms} setForms={setForms}/>} {tab==='employeeNotifications'&&<Notifications current={current} notifications={notifications}/>}</main></div></div>
}
const labels={dashboard:'الرئيسية',employees:'الموظفون',users:'المستخدمون والصلاحيات',locations:'مواقع العمل',attendance:'الحضور GPS',requests:'الطلبات',forms:'النماذج الذكية',payroll:'البيرول',reports:'التقارير',notifications:'الإشعارات',email:'الإيميل',license:'التفعيل والترخيص',maintenance:'النسخ والصيانة',security:'الأمان',settings:'الإعدادات',employeeHome:'واجهة الموظف',employeeAttendance:'بصمة الموظف',employeeRequests:'طلباتي',employeeForms:'نماذجي',employeeNotifications:'إشعاراتي'};
const icons={dashboard:BarChart3,employees:Users,users:Lock,locations:MapPin,attendance:Clock,requests:Workflow,forms:FileText,payroll:DollarSign,reports:BarChart3,notifications:Bell,email:Mail,license:KeyRound,maintenance:Download,security:ShieldCheck,settings:Settings,employeeHome:UserCheck,employeeAttendance:Clock,employeeRequests:Workflow,employeeForms:FileText,employeeNotifications:Bell};
function Login({users,setCurrent,settings,license,trial}){const[u,setU]=useState(''),[p,setP]=useState('');function go(e){e.preventDefault();const user=users.find(x=>x.username===u&&x.password===p);if(!user)return alert('بيانات الدخول غير صحيحة');setCurrent(user)}return <div className="login"><form className="loginCard" onSubmit={go}><h1>{settings.systemName}</h1><p className="muted">{settings.company}</p><div className="alert">الحالة: {license.active?'نسخة مفعلة':`تجربة - متبقي ${trial.daysLeft} يوم`}</div><label>اسم المستخدم</label><input value={u} onChange={e=>setU(e.target.value)} autoComplete="username"/><label>كلمة المرور</label><input type="password" value={p} onChange={e=>setP(e.target.value)} autoComplete="current-password"/><br/><br/><button className="btn green" style={{width:'100%'}}>دخول</button></form></div>}
function Header({settings,current,logout,license,trial}){return <header className="header"><div className="brand"><div className="logo">{settings.logo?<img src={settings.logo}/>:settings.watermark?.[0]||'N'}</div><div><h1>{settings.systemName}</h1><p>{settings.company} — {settings.activity} — {current.name} / {current.role}</p></div></div><div className="badges"><span className={`badge ${license.active?'green':'yellow'}`}>{license.active?'Activated':`Trial ${trial.daysLeft}d`}</span><span className="badge blue">White Label</span><span className="badge purple">Payroll</span><button className="btn red" onClick={logout}>خروج</button></div></header>}
function Nav({id,label,icon:Icon,tab,setTab}){return <button className={`nav ${tab===id?'active':''}`} onClick={()=>setTab(id)}><Icon size={19}/>{label}</button>}
function Card({title,icon:Icon,actions,children}){return <section className="card"><div className="title"><h2>{Icon&&<Icon size={21} style={{verticalAlign:'middle',marginLeft:8}}/>}{title}</h2><div className="noPrint">{actions}</div></div>{children}</section>}
function Input({label,value,onChange,type='text'}){return <div><label>{label}</label><input type={type} value={value||''} onChange={e=>onChange(e.target.value)}/></div>}
function Table({headers,rows}){return <div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Badge({children,tone='blue'}){return <span className={`badge ${tone}`}>{children}</span>}
function Stat({title,value,icon:Icon,tone,note}){return <div className="card stat"><span className={`badge ${tone}`}><Icon size={22}/></span><div className="muted">{title}</div><div className="num">{value}</div><div className="muted">{note}</div></div>}
function Dashboard({employees,attendance,requests,payroll}){return <div className="grid4"><Stat title="الموظفون" value={employees.length} icon={Users} tone="blue" note="فعلي"/><Stat title="البصمات" value={attendance.length} icon={Clock} tone="green" note="GPS"/><Stat title="الطلبات" value={requests.length} icon={Workflow} tone="yellow" note="Workflow"/><Stat title="مسيرات الرواتب" value={payroll.length} icon={DollarSign} tone="purple" note="Payroll"/></div>}
function Employees({employees,setEmployees,users,setUsers,addAudit}){const empty={employeeCode:'',name:'',iqama:'',role:'',department:'',project:'',branch:'',email:'',phone:'',basicSalary:'4000',housing:'0',transport:'0'};const[f,setF]=useState(empty),[edit,setEdit]=useState(null);function saveEmp(e){e.preventDefault();if(!f.employeeCode||!f.name)return alert('الكود والاسم مطلوبان');if(edit){setEmployees(p=>p.map(x=>x.id===edit?{...x,...f}:x));setEdit(null)}else setEmployees(p=>[{id:uid('EMP'),...f,createdAt:today()},...p]);setF(empty)}function userFor(e){if(users.some(u=>u.employeeId===e.id))return alert('له مستخدم بالفعل');setUsers(p=>[...p,{id:uid('U'),username:e.employeeCode,password:'123456',role:'employee',name:e.name,employeeId:e.id,email:e.email}]);alert(`تم إنشاء دخول الموظف: ${e.employeeCode} / 123456`)}return <><Card title="إضافة / تعديل موظف" icon={Plus}><form className="formGrid" onSubmit={saveEmp}>{Object.entries({employeeCode:'كود الموظف',name:'اسم الموظف',iqama:'رقم الإقامة',role:'الوظيفة',department:'القسم',project:'المشروع',branch:'الفرع',email:'الإيميل',phone:'الجوال',basicSalary:'الراتب الأساسي',housing:'بدل السكن',transport:'بدل النقل'}).map(([k,l])=><Input key={k} label={l} value={f[k]} onChange={v=>setF({...f,[k]:v})}/>) }<button className="btn green">حفظ</button></form></Card><Card title="قائمة الموظفين" icon={Users}>{employees.length?<Table headers={['الكود','الاسم','الوظيفة','المشروع','الراتب','إجراءات']} rows={employees.map(e=>[e.employeeCode,e.name,e.role,e.project,e.basicSalary,<div className="badges"><button className="btn light" onClick={()=>{setF(e);setEdit(e.id)}}>تعديل</button><button className="btn yellow" onClick={()=>userFor(e)}>يوزر</button><button className="btn red" onClick={()=>setEmployees(p=>p.filter(x=>x.id!==e.id))}>حذف</button></div>])}/>:<div className="empty">أضف أول موظف.</div>}</Card></>}
function UsersAdmin({users,setUsers,employees}){return <Card title="المستخدمون" icon={Lock}><Table headers={['Username','الاسم','الدور','موظف','حذف']} rows={users.map(u=>[u.username,u.name,u.role,u.employeeId||'-',<button className="btn red" onClick={()=>setUsers(p=>p.filter(x=>x.id!==u.id))}>حذف</button>])}/></Card>}
function Locations({locations,setLocations}){const[f,setF]=useState({name:'',lat:'',lng:'',radius:'100'});function geo(){navigator.geolocation?.getCurrentPosition(pos=>setF({...f,lat:pos.coords.latitude,lng:pos.coords.longitude}),()=>alert('اسمح بالموقع'))}function add(){if(!f.name||!f.lat||!f.lng)return alert('البيانات ناقصة');setLocations(p=>[...p,{id:uid('LOC'),...f}]);setF({name:'',lat:'',lng:'',radius:'100'})}return <><Card title="مواقع العمل" icon={MapPin} actions={<button className="btn light" onClick={geo}>موقعي الحالي</button>}><div className="formGrid"><Input label="اسم الموقع" value={f.name} onChange={v=>setF({...f,name:v})}/><Input label="Latitude" value={f.lat} onChange={v=>setF({...f,lat:v})}/><Input label="Longitude" value={f.lng} onChange={v=>setF({...f,lng:v})}/><Input label="المسافة بالمتر" value={f.radius} onChange={v=>setF({...f,radius:v})}/><button className="btn green" onClick={add}>إضافة موقع</button></div></Card><Card title="المواقع المحفوظة" icon={Building2}>{locations.length?<Table headers={['الموقع','Lat','Lng','Radius','حذف']} rows={locations.map(l=>[l.name,l.lat,l.lng,l.radius,<button className="btn red" onClick={()=>setLocations(p=>p.filter(x=>x.id!==l.id))}>حذف</button>])}/>:<div className="empty">لا توجد مواقع.</div>}</Card></>}
function Attendance({employeeMode,current,employees,locations,attendance,setAttendance,settings,addAudit,notify}){const[empId,setEmpId]=useState(employeeMode?current.employeeId:''),[locId,setLocId]=useState('');const emp=employees.find(e=>e.id===empId);const loc=locations.find(l=>l.id===locId)||locations[0];const rec=emp?attendance.find(a=>a.employeeId===emp.id&&a.date===today()):null;function punch(type){if(!emp)return alert('اختر موظف');if(!loc)return alert('أضف موقع عمل');navigator.geolocation?.getCurrentPosition(pos=>{const d=distanceMeters(pos.coords.latitude,pos.coords.longitude,loc.lat,loc.lng);if(d>Number(loc.radius))return alert(`خارج نطاق البصمة: ${d} متر / المسموح ${loc.radius}`);if(type==='in'){if(rec?.checkIn)return alert('تم تسجيل الحضور');const late=nowTime()>settings.checkInEnd;setAttendance(p=>[{id:uid('ATT'),employeeId:emp.id,employeeName:emp.name,locationName:loc.name,date:today(),month:month(),checkIn:nowTime(),checkOut:'',status:late?'late':'present',delayMinutes:late?15:0,distance:d},...p]);if(late)notify({toRole:'hr',title:'تأخير موظف',message:`${emp.name} حضر متأخر`})}else{if(!rec)return alert('لا يوجد حضور');setAttendance(p=>p.map(a=>a.id===rec.id?{...a,checkOut:nowTime()}:a))}},()=>alert('اسمح بالموقع GPS'))}return <><Card title="بصمة GPS" icon={Clock} actions={<div className="badges"><button className="btn green" onClick={()=>punch('in')}><LogIn size={16}/>حضور</button><button className="btn red" onClick={()=>punch('out')}><LogOut size={16}/>انصراف</button></div>}><div className="grid3">{!employeeMode&&<div><label>الموظف</label><select value={empId} onChange={e=>setEmpId(e.target.value)}><option value="">اختر</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div>}<div><label>موقع العمل</label><select value={locId} onChange={e=>setLocId(e.target.value)}><option value="">أول موقع</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="card"><b>{rec?.checkIn?`حضور ${rec.checkIn}`:'لم يسجل اليوم'}</b></div></div></Card><Card title="سجل الحضور" icon={History}>{attendance.length?<Table headers={['التاريخ','الموظف','الموقع','حضور','انصراف','الحالة','مسافة']} rows={attendance.filter(a=>employeeMode?a.employeeId===current.employeeId:true).map(a=>[a.date,a.employeeName,a.locationName,a.checkIn,a.checkOut||'--',a.status,a.distance+'م'])}/>:<div className="empty">لا توجد بصمات.</div>}</Card></>}
function Requests({employeeMode,current,employees,requests,setRequests,notify}){const[f,setF]=useState({employeeId:employeeMode?current.employeeId:'',type:'leave',notes:''});const list=requests.filter(r=>employeeMode?r.employeeId===current.employeeId:true);function add(){const e=employees.find(x=>x.id===f.employeeId);if(!e)return alert('اختر موظف');setRequests(p=>[{id:uid('REQ'),...f,employeeName:e.name,status:'pending',createdAt:today()},...p]);notify({toRole:'hr',title:'طلب جديد',message:`${e.name} أرسل ${getFormTemplate(f.type).title}`})}return <><Card title="إرسال طلب" icon={Workflow}><div className="formGrid">{!employeeMode&&<div><label>الموظف</label><select value={f.employeeId} onChange={e=>setF({...f,employeeId:e.target.value})}><option value="">اختر</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div>}<div><label>نوع الطلب</label><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{Object.entries(FORM_TEMPLATES).map(([k,v])=><option value={k} key={k}>{v.title}</option>)}</select></div><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><button className="btn green" onClick={add}>إرسال</button></div></Card><Card title="الطلبات" icon={Workflow}>{list.length?<Table headers={['رقم','الموظف','النوع','الحالة','ملاحظات']} rows={list.map(r=>[r.id,r.employeeName,getFormTemplate(r.type).title,r.status,r.notes])}/>:<div className="empty">لا توجد طلبات.</div>}</Card></>}
function Forms({employeeMode,current,settings,employees,forms,setForms}){const[type,setType]=useState('advance'),[empId,setEmpId]=useState(employeeMode?current.employeeId:''),[data,setData]=useState({});const emp=employees.find(e=>e.id===empId);const fields=getFormFields(type);function saveF(){if(!emp)return alert('اختر موظف');setForms(p=>[{id:uid('FORM'),employeeId:emp.id,employeeName:emp.name,title:getFormTemplate(type).title,type,createdAt:today()},...p])}return <><div className="grid2"><Card title="النماذج الذكية" icon={FileText} actions={<div className="badges"><button className="btn green" onClick={saveF}>حفظ</button><button className="btn" onClick={()=>window.print()}><Printer size={16}/>PDF</button></div>}><div className="formGrid">{!employeeMode&&<div><label>الموظف</label><select value={empId} onChange={e=>setEmpId(e.target.value)}><option value="">اختر</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></div>}<div><label>النموذج</label><select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(FORM_TEMPLATES).map(([k,v])=><option value={k} key={k}>{v.title}</option>)}</select></div>{fields.map(f=><Input key={f} label={fieldLabels[f]||f} value={data[f]||''} onChange={v=>setData({...data,[f]:v})}/>)}</div></Card><Paper settings={settings} employee={emp} type={type} data={data}/></div></>}
const fieldLabels={amount:'المبلغ',reason:'السبب',from:'من تاريخ',to:'إلى تاريخ',permissionDate:'تاريخ الإذن',fromTime:'من الساعة',toTime:'إلى الساعة',custody:'العهدة',violation:'المخالفة',returnDate:'تاريخ المباشرة',destination:'الوجهة',purpose:'الغرض',lastDay:'آخر يوم عمل',date:'التاريخ'};
function Paper({settings,employee,type,data}){return <div className="paper"><div className="watermark">{settings.watermark}</div><div className="paperHeader"><div><b>{settings.company}</b><br/><span className="muted">نشاط الشركة: {settings.activity}</span></div><div className="paperLogo">{settings.logo?<img src={settings.logo}/>:settings.watermark?.[0]||'N'}</div></div><h1 style={{textAlign:'center'}}>{getFormTemplate(type).title}</h1>{employee?<><div className="meta"><Meta label="اسم الموظف" value={employee.name}/><Meta label="كود الموظف" value={employee.employeeCode}/><Meta label="رقم الإقامة" value={employee.iqama||'-'}/><Meta label="القسم" value={employee.department||'-'}/></div><div className="bodyText">{getFormBody(type,{employee,settings,...data})}</div><div className="signatures"><div className="sig">توقيع الموظف</div><div className="sig">مسؤول الموارد البشرية</div><div className="sig">اعتماد الإدارة</div></div></>:<div className="empty">اختر موظف.</div>}</div>}
function Meta({label,value}){return <div className="metaBox"><span className="muted">{label}: </span><b>{value}</b></div>}
function Payroll({employees,attendance,payroll,setPayroll,settings}){const[period,setPeriod]=useState(month());function calc(){const rows=employees.map(e=>{const att=attendance.filter(a=>a.employeeId===e.id&&a.month===period);return{id:uid('PAY'),period,employeeName:e.name,...calculatePayroll({basicSalary:e.basicSalary,housing:e.housing,transport:e.transport,presentDays:new Set(att.map(a=>a.date)).size,workingDays:settings.workingDays,lateMinutes:att.reduce((s,a)=>s+Number(a.delayMinutes||0),0),overtimeRate:settings.overtimeRate})}});setPayroll(p=>[...rows,...p.filter(x=>x.period!==period)])}return <Card title="البيرول" icon={DollarSign} actions={<button className="btn green" onClick={calc}>احتساب</button>}><Input label="الشهر" type="month" value={period} onChange={setPeriod}/><br/>{payroll.filter(p=>p.period===period).length?<Table headers={['الموظف','الأساسي','الحضور','الغياب','خصم التأخير','خصم الغياب','الصافي']} rows={payroll.filter(p=>p.period===period).map(p=>[p.employeeName,p.basic,p.presentDays,p.absentDays,p.lateDeduction,p.absenceDeduction,p.net])}/>:<div className="empty">لا يوجد مسير.</div>}</Card>}
function Reports(p){return <Dashboard {...p}/>}
function Notifications({current,notifications}){const list=current?notifications.filter(n=>n.toEmployeeId===current.employeeId||n.toRole===current.role):notifications;return <Card title="الإشعارات" icon={Bell}>{list.length?<Table headers={['تاريخ','وقت','العنوان','الرسالة']} rows={list.map(n=>[n.date,n.time,n.title,n.message])}/>:<div className="empty">لا توجد إشعارات.</div>}</Card>}
function Email({emails}){return <Card title="إيميلات النظام" icon={Mail}>{emails.length?<Table headers={['إلى','العنوان','الحالة','التاريخ']} rows={emails.map(e=>[e.to,e.subject,e.status,e.date])}/>:<div className="empty">لا توجد إيميلات.</div>}</Card>}
function LicensePanel({settings,setSettings,license,setLicense}){const[mid]=useState(machineId()),[code,setCode]=useState(''),[client,setClient]=useState(settings.company),[expiry,setExpiry]=useState('2099-12-31');function gen(){setCode(generateActivationCode({clientName:client,systemName:settings.systemName,machine:mid,expiry,secret:settings.licenseSecret}))}function activate(){const r=validateActivationCode({code:license.code,clientName:settings.company,systemName:settings.systemName,machine:mid,secret:settings.licenseSecret});if(!r.valid)return alert(r.reason);setLicense({...license,active:true,plan:r.plan,expiry:r.expiry});alert('تم التفعيل')}return <><Card title="تفعيل النسخة" icon={KeyRound}><div className="grid2"><Input label="Machine ID" value={mid} onChange={()=>{}}/><Input label="كود التفعيل" value={license.code} onChange={v=>setLicense({...license,code:v})}/><button className="btn green" onClick={activate}>تفعيل</button></div></Card><Card title="مولد أكواد التفعيل" icon={KeyRound}><div className="formGrid"><Input label="اسم العميل" value={client} onChange={setClient}/><Input label="انتهاء التفعيل" type="date" value={expiry} onChange={setExpiry}/><button className="btn" onClick={gen}>توليد كود</button><textarea value={code} readOnly rows="3"/></div></Card></>}
function Maintenance({data}){function backup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nabny-hr-backup.json';a.click()}return <Card title="النسخ الاحتياطي والصيانة" icon={Download}><div className="badges"><button className="btn green" onClick={backup}><Download size={16}/>تحميل نسخة احتياطية</button><button className="btn light" onClick={()=>alert('تم فحص البيانات: لا توجد أخطاء ظاهرة')}>فحص وصيانة</button><button className="btn yellow" onClick={()=>alert('الأرشفة الشهرية تحفظ عند احتساب البيرول')}>أرشفة شهرية</button></div></Card>}
function Security({audit}){return <Card title="سجل النشاطات" icon={ShieldCheck}>{audit.length?<Table headers={['التاريخ','الوقت','المستخدم','الحركة','المخاطر']} rows={audit.map(a=>[a.date,a.time,a.actor,a.action,a.risk])}/>:<div className="empty">لا توجد حركات.</div>}</Card>}
function SystemSettings({settings,setSettings}){function logo(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setSettings({...settings,logo:r.result});r.readAsDataURL(f)}function newCompany(){if(confirm('إنشاء نسخة شركة جديدة سيمسح بيانات الشركة الحالية من المتصفح فقط. هل تريد المتابعة؟')){localStorage.clear();location.reload()}}return <Card title="الإعدادات و White Label" icon={Settings} actions={<button className="btn yellow" onClick={newCompany}>نسخة لشركة أخرى</button>}><div className="formGrid"><Input label="اسم السيستم" value={settings.systemName} onChange={v=>setSettings({...settings,systemName:v})}/><Input label="اسم الشركة" value={settings.company} onChange={v=>setSettings({...settings,company:v})}/><Input label="نشاط الشركة" value={settings.activity} onChange={v=>setSettings({...settings,activity:v})}/><Input label="الخلفية المائية" value={settings.watermark} onChange={v=>setSettings({...settings,watermark:v})}/><Input label="إيميل HR" value={settings.hrEmail} onChange={v=>setSettings({...settings,hrEmail:v})}/><Input label="إيميل الإدارة" value={settings.adminEmail} onChange={v=>setSettings({...settings,adminEmail:v})}/><Input label="أيام التجربة" value={settings.trialDays} onChange={v=>setSettings({...settings,trialDays:v})}/><Input label="سر التفعيل" value={settings.licenseSecret} onChange={v=>setSettings({...settings,licenseSecret:v})}/><div><label>اللوجو</label><input type="file" accept="image/*" onChange={logo}/></div></div></Card>}
function EmployeeHome({current,employees,attendance,requests,notifications}){const emp=employees.find(e=>e.id===current.employeeId);return <><Card title="صفحة الموظف" icon={UserCheck}>{emp?<div className="grid3"><div className="card"><b>{emp.name}</b></div><div className="card"><b>{emp.role||'-'}</b></div><div className="card"><b>{emp.project||'-'}</b></div></div>:<div className="empty">هذا المستخدم غير مربوط بموظف.</div>}</Card><div className="grid3"><Stat title="بصماتي" value={attendance.filter(a=>a.employeeId===current.employeeId).length} icon={Clock} tone="green" note="GPS"/><Stat title="طلباتي" value={requests.filter(r=>r.employeeId===current.employeeId).length} icon={Workflow} tone="yellow" note="طلبات"/><Stat title="إشعاراتي" value={notifications.filter(n=>n.toEmployeeId===current.employeeId).length} icon={Bell} tone="purple" note="تنبيهات"/></div></>}
