export const FORM_TEMPLATES = {
  advance:{title:"طلب سلفة مالية",fields:["amount","reason"],body:({employee,amount="________",reason="________"})=>`أتقدم أنا الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، بطلب صرف سلفة مالية بمبلغ وقدره (${amount}) ريال سعودي، وذلك بسبب: ${reason}. وأتعهد بالموافقة على خصم قيمة السلفة من راتبي وفق الآلية المعتمدة لدى إدارة الشركة، ولا يعتبر هذا الطلب مستند صرف إلا بعد اعتماده من الإدارة المختصة.`},
  leave:{title:"طلب إجازة",fields:["from","to","reason"],body:({employee,from="____/____/____",to="____/____/____",reason="________"})=>`أتقدم أنا الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، بطلب إجازة من تاريخ ${from} إلى تاريخ ${to}، وذلك بسبب: ${reason}. وأتعهد بتسليم الأعمال والعهد قبل بداية الإجازة والعودة إلى العمل في الموعد المحدد، على أن يخضع الطلب لاعتماد المدير المباشر وإدارة الموارد البشرية.`},
  permission:{title:"طلب إذن",fields:["permissionDate","fromTime","toTime","reason"],body:({employee,permissionDate="____/____/____",fromTime="__:__",toTime="__:__",reason="________"})=>`أتقدم أنا الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، بطلب إذن خروج / تأخير بتاريخ ${permissionDate} من الساعة ${fromTime} إلى الساعة ${toTime}، وذلك بسبب: ${reason}. ولا يعتبر الإذن معتمدًا إلا بعد موافقة المدير المباشر وتسجيله بالنظام.`},
  salary:{title:"خطاب تعريف راتب",fields:[],body:({employee,settings})=>`تشهد ${settings?.company||"شركة نبني للمقاولات"} بأن الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، يعمل لدينا بوظيفة / ${employee?.role||"________"}، ويتقاضى راتبًا أساسيًا قدره (${employee?.basicSalary||"________"}) ريال سعودي. وقد أعطي هذا الخطاب بناءً على طلبه دون أدنى مسؤولية على الشركة تجاه الغير.`},
  custody:{title:"نموذج استلام عهدة",fields:["custody"],body:({employee,custody="________"})=>`أقر أنا الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، بأنني استلمت العهدة التالية: ${custody}. وأتعهد بالمحافظة عليها واستخدامها لأغراض العمل فقط وإعادتها عند الطلب أو عند انتهاء العلاقة العملية.`},
  clearance:{title:"إخلاء طرف",fields:[],body:({employee,settings})=>`تفيد ${settings?.company||"شركة نبني للمقاولات"} بأنه تم إنهاء إجراءات إخلاء طرف الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، بعد مراجعة الإدارات المختصة والتأكد من تسليم ما بعهدته وفق سجلات الشركة.`},
  warning:{title:"إنذار موظف",fields:["violation"],body:({employee,violation="________"})=>`بناءً على ما تم رصده بشأن الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، فقد تقرر توجيه هذا الإنذار بسبب: ${violation}. ويعد هذا الإنذار تنبيهًا رسميًا بضرورة الالتزام بأنظمة ولوائح العمل المعتمدة لدى الشركة.`},
  returnWork:{title:"مباشرة عمل",fields:["returnDate"],body:({employee,returnDate="____/____/____"})=>`نفيد بأن الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، قد باشر عمله بتاريخ ${returnDate} بعد انتهاء فترة الإجازة / الانقطاع / التكليف، وتم إثبات مباشرته في سجلات الحضور والموارد البشرية بالشركة.`},
  travel:{title:"طلب مهمة عمل / سفر",fields:["destination","from","to","purpose"],body:({employee,destination="________",from="____/____/____",to="____/____/____",purpose="________"})=>`أتقدم أنا الموظف / ${employee?.name||"________"} بطلب مهمة عمل إلى ${destination} خلال الفترة من ${from} إلى ${to}، وذلك لغرض: ${purpose}. وأتعهد بالالتزام بتعليمات المهمة وتقديم ما يثبت إنجازها وفق سياسات الشركة.`},
  resignation:{title:"طلب استقالة",fields:["lastDay","reason"],body:({employee,lastDay="____/____/____",reason="________"})=>`أتقدم أنا الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، بطلب الاستقالة من العمل، على أن يكون آخر يوم عمل بتاريخ ${lastDay}. سبب الاستقالة: ${reason}. وأتعهد بتسليم جميع العهد والأعمال قبل تاريخ انتهاء العمل.`},
  experience:{title:"شهادة خبرة",fields:["from","to"],body:({employee,from="____/____/____",to="____/____/____"})=>`تشهد شركة نبني للمقاولات بأن الموظف / ${employee?.name||"________"}، عمل لديها بوظيفة / ${employee?.role||"________"} خلال الفترة من ${from} إلى ${to}. وقد أعطيت له هذه الشهادة بناءً على طلبه.`},
  violation:{title:"محضر مخالفة",fields:["violation","date"],body:({employee,violation="________",date="____/____/____"})=>`في تاريخ ${date} تم تحرير هذا المحضر بشأن الموظف / ${employee?.name||"________"}، كود الموظف / ${employee?.employeeCode||"________"}، وذلك بسبب المخالفة التالية: ${violation}. وتم إبلاغ الموظف بالمخالفة لاتخاذ الإجراء النظامي وفق لوائح الشركة.`}
};
export const getFormTemplate=(type)=>FORM_TEMPLATES[type]||FORM_TEMPLATES.salary;
export const getFormBody=(type,data)=>getFormTemplate(type).body(data).replace(/\n\s+/g,"\\n").trim();
export const getFormFields=(type)=>getFormTemplate(type).fields||[];
